// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aabu_project.Data;

#nullable disable

namespace aabu_project.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260430123034_AddRelatedIdToNotification")]
    partial class AddRelatedIdToNotification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("aabu_project.Models.ApplicationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CandidateStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId", "JobId")
                        .IsUnique()
                        .HasDatabaseName("UX_ApplicationJobs_UserId_JobId");

                    b.ToTable("ApplicationJobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CandidateStatus = "Applied",
                            CompanyStatus = "Under Review",
                            Cv = "ahmad_cv.pdf",
                            Date = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobId = 1,
                            Note = "Strong candidate with relevant experience.",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CandidateStatus = "Applied",
                            CompanyStatus = "Shortlisted",
                            Cv = "sara_cv.pdf",
                            Date = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobId = 2,
                            Note = "Great portfolio.",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CandidateStatus = "Applied",
                            CompanyStatus = "Under Review",
                            Cv = "omar_cv.pdf",
                            Date = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobId = 4,
                            Note = "Solid marketing background.",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("aabu_project.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Design"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Healthcare"
                        });
                });

            modelBuilder.Entity("aabu_project.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GraduationYear")
                        .HasColumnType("int");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EducationLevel = "Bachelor's",
                            GraduationYear = 2017,
                            Institution = "University of Dubai",
                            ResumeId = 1
                        },
                        new
                        {
                            Id = 2,
                            EducationLevel = "Bachelor's",
                            GraduationYear = 2020,
                            Institution = "Abu Dhabi University",
                            ResumeId = 2
                        },
                        new
                        {
                            Id = 3,
                            EducationLevel = "Master's",
                            GraduationYear = 2019,
                            Institution = "American University of Sharjah",
                            ResumeId = 3
                        });
                });

            modelBuilder.Entity("aabu_project.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Dubai Tech Solutions",
                            JobName = "Senior Software Engineer",
                            ResumeId = 1,
                            StartDate = "2020-03-01"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Gulf Digital Agency",
                            EndDate = "2020-02-28",
                            JobName = "Software Developer",
                            ResumeId = 1,
                            StartDate = "2017-06-01"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Creative Studio UAE",
                            JobName = "UI/UX Designer",
                            ResumeId = 2,
                            StartDate = "2021-01-01"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Growth Agency",
                            JobName = "Digital Marketing Specialist",
                            ResumeId = 3,
                            StartDate = "2019-08-01"
                        });
                });

            modelBuilder.Entity("aabu_project.Models.FollowCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FollowedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId", "CompanyId")
                        .IsUnique()
                        .HasDatabaseName("UX_FollowCompany_UserId_CompanyId");

                    b.ToTable("FollowCompanies");
                });

            modelBuilder.Entity("aabu_project.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSalaryNegotiable")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("PostedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SearchKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.Property<string>("WorkMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Company = "Dubai Tech Solutions",
                            Description = "Build amazing UIs for our enterprise platform used by thousands of clients worldwide.",
                            IsSalaryNegotiable = false,
                            Location = "Remote",
                            PostedDate = new DateTimeOffset(new DateTime(2026, 4, 30, 15, 30, 32, 564, DateTimeKind.Unspecified).AddTicks(4968), new TimeSpan(0, 3, 0, 0, 0)),
                            Requirements = "5+ years React, TypeScript, Redux, REST APIs",
                            Responsibilities = "Develop and maintain React applications, collaborate with backend teams, conduct code reviews, mentor junior developers.",
                            SalaryMax = 160000m,
                            SalaryMin = 120000m,
                            Status = "Active",
                            Title = "Senior React Developer",
                            Type = "Full Time",
                            UserId = 3,
                            ViewsCount = 0,
                            WorkMode = "Remote"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Company = "Creative Studio UAE",
                            Description = "Design clean, intuitive interfaces for web and mobile applications.",
                            IsSalaryNegotiable = false,
                            Location = "Abu Dhabi",
                            PostedDate = new DateTimeOffset(new DateTime(2026, 4, 30, 15, 30, 32, 564, DateTimeKind.Unspecified).AddTicks(4985), new TimeSpan(0, 3, 0, 0, 0)),
                            Requirements = "3+ years experience, Figma, Adobe XD, user research skills",
                            Responsibilities = "Create wireframes, prototypes, and high-fidelity designs. Conduct user research and usability testing.",
                            SalaryMax = 140000m,
                            SalaryMin = 100000m,
                            Status = "Active",
                            Title = "UI/UX Designer",
                            Type = "Full Time",
                            UserId = 3,
                            ViewsCount = 0,
                            WorkMode = "On-site"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Company = "Tech Corp",
                            Description = "Develop and maintain scalable ASP.NET Core APIs for our cloud platform.",
                            IsSalaryNegotiable = false,
                            Location = "Dubai",
                            PostedDate = new DateTimeOffset(new DateTime(2026, 4, 30, 15, 30, 32, 564, DateTimeKind.Unspecified).AddTicks(4995), new TimeSpan(0, 3, 0, 0, 0)),
                            Requirements = "4+ years .NET, C#, Entity Framework, SQL Server",
                            Responsibilities = "Design RESTful APIs, optimize database queries, implement security best practices.",
                            SalaryMax = 150000m,
                            SalaryMin = 110000m,
                            Status = "Active",
                            Title = "Backend .NET Developer",
                            Type = "Full Time",
                            UserId = 3,
                            ViewsCount = 0,
                            WorkMode = "Hybrid"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Company = "Growth Agency",
                            Description = "Lead our digital marketing efforts across all channels.",
                            IsSalaryNegotiable = false,
                            Location = "Sharjah",
                            PostedDate = new DateTimeOffset(new DateTime(2026, 4, 30, 15, 30, 32, 564, DateTimeKind.Unspecified).AddTicks(5003), new TimeSpan(0, 3, 0, 0, 0)),
                            Requirements = "5+ years digital marketing, Google Ads, Meta Ads, analytics tools",
                            Responsibilities = "Manage SEO/SEM campaigns, oversee social media strategy, analyze performance metrics.",
                            SalaryMax = 120000m,
                            SalaryMin = 90000m,
                            Status = "Active",
                            Title = "Digital Marketing Manager",
                            Type = "Full Time",
                            UserId = 3,
                            ViewsCount = 0,
                            WorkMode = "On-site"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Company = "Finance Global",
                            Description = "Analyze financial data and provide insights to support business decisions.",
                            IsSalaryNegotiable = false,
                            Location = "Dubai",
                            PostedDate = new DateTimeOffset(new DateTime(2026, 4, 30, 15, 30, 32, 564, DateTimeKind.Unspecified).AddTicks(5011), new TimeSpan(0, 3, 0, 0, 0)),
                            Requirements = "CFA or CPA preferred, Excel, Power BI, 3+ years experience",
                            Responsibilities = "Prepare financial reports, build forecasting models, monitor KPIs.",
                            SalaryMax = 130000m,
                            SalaryMin = 95000m,
                            Status = "Active",
                            Title = "Financial Analyst",
                            Type = "Full Time",
                            UserId = 3,
                            ViewsCount = 0,
                            WorkMode = "On-site"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Company = "App Builders",
                            Description = "Build cross-platform mobile apps for iOS and Android.",
                            IsSalaryNegotiable = false,
                            Location = "Remote",
                            PostedDate = new DateTimeOffset(new DateTime(2026, 4, 30, 15, 30, 32, 564, DateTimeKind.Unspecified).AddTicks(5018), new TimeSpan(0, 3, 0, 0, 0)),
                            Requirements = "3+ years React Native, TypeScript, push notifications, app store publishing",
                            Responsibilities = "Develop features, integrate APIs, optimize app performance.",
                            SalaryMax = 110000m,
                            SalaryMin = 80000m,
                            Status = "Active",
                            Title = "Mobile Developer (React Native)",
                            Type = "Contract",
                            UserId = 3,
                            ViewsCount = 0,
                            WorkMode = "Remote"
                        });
                });

            modelBuilder.Entity("aabu_project.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 30, 15, 0, 32, 564, DateTimeKind.Unspecified).AddTicks(5397), new TimeSpan(0, 3, 0, 0, 0)),
                            IsRead = false,
                            Message = "Your application for Senior React Developer has been received.",
                            Receiver = "Job Seeker",
                            Title = "Application Received",
                            Type = "info",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 30, 13, 30, 32, 564, DateTimeKind.Unspecified).AddTicks(5423), new TimeSpan(0, 3, 0, 0, 0)),
                            IsRead = true,
                            Message = "An employer viewed your profile.",
                            Receiver = "Job Seeker",
                            Title = "Profile Viewed",
                            Type = "info",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 15, 30, 32, 564, DateTimeKind.Unspecified).AddTicks(5434), new TimeSpan(0, 3, 0, 0, 0)),
                            IsRead = false,
                            Message = "A new UI/UX Designer position matches your profile.",
                            Receiver = "Job Seeker",
                            Title = "New Job Match",
                            Type = "success",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 27, 15, 30, 32, 564, DateTimeKind.Unspecified).AddTicks(5443), new TimeSpan(0, 3, 0, 0, 0)),
                            IsRead = false,
                            Message = "Ahmad Al-Hassan applied for Senior React Developer.",
                            Receiver = "Employer",
                            Title = "New Application",
                            Type = "info",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("aabu_project.Models.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Resumes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Passionate software engineer with expertise in full-stack development and cloud technologies.",
                            Email = "ahmad@example.com",
                            Location = "Dubai, UAE",
                            Name = "Ahmad Al-Hassan",
                            Phone = "+971501234567",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Creative designer with a strong eye for detail and a passion for crafting exceptional user experiences.",
                            Email = "sara@example.com",
                            Location = "Abu Dhabi, UAE",
                            Name = "Sara Malik",
                            Phone = "+971502345678",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Results-driven marketing professional with a proven track record in growing digital presence.",
                            Email = "omar@example.com",
                            Location = "Sharjah, UAE",
                            Name = "Omar Khalid",
                            Phone = "+971503456789",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("aabu_project.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Job Seeker",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Job Seeker",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Employer",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            RoleName = "Job Seeker",
                            UserId = 4
                        },
                        new
                        {
                            Id = 100,
                            RoleName = "Admin",
                            UserId = 100
                        });
                });

            modelBuilder.Entity("aabu_project.Models.SavedJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId", "JobId")
                        .IsUnique()
                        .HasDatabaseName("UX_SavedJobs_UserId_JobId");

                    b.ToTable("SavedJobs");
                });

            modelBuilder.Entity("aabu_project.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "React",
                            ResumeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "C#",
                            ResumeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "ASP.NET Core",
                            ResumeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "SQL",
                            ResumeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Figma",
                            ResumeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Adobe XD",
                            ResumeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Prototyping",
                            ResumeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "SEO",
                            ResumeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "Google Ads",
                            ResumeId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "Meta Ads",
                            ResumeId = 3
                        });
                });

            modelBuilder.Entity("aabu_project.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Github")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 30, 15, 30, 32, 564, DateTimeKind.Unspecified).AddTicks(4681), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Senior software engineer with 8 years of experience.",
                            Email = "ahmad@example.com",
                            Github = "github.com/ahmad",
                            Industry = "Software",
                            LinkedIn = "linkedin.com/in/ahmad",
                            Location = "Dubai, UAE",
                            Name = "Ahmad Al-Hassan",
                            Pass = "password",
                            Phone = "+971501234567",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 30, 15, 30, 32, 564, DateTimeKind.Unspecified).AddTicks(4750), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Creative UI/UX designer passionate about user-centered design.",
                            Email = "sara@example.com",
                            Industry = "Design",
                            Location = "Abu Dhabi, UAE",
                            Name = "Sara Malik",
                            Pass = "password",
                            Phone = "+971502345678",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 30, 15, 30, 32, 564, DateTimeKind.Unspecified).AddTicks(4761), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Leading technology company specializing in enterprise solutions.",
                            Email = "hr@techcorp.com",
                            Industry = "Technology",
                            Location = "Dubai, UAE",
                            Name = "Tech Corp",
                            Pass = "password",
                            Status = "Active",
                            Website = "techcorp.com"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 30, 15, 30, 32, 564, DateTimeKind.Unspecified).AddTicks(4770), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Digital marketing specialist with expertise in SEO and social media.",
                            Email = "omar@example.com",
                            Industry = "Marketing",
                            Location = "Sharjah, UAE",
                            Name = "Omar Khalid",
                            Pass = "password",
                            Phone = "+971503456789",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 30, 15, 30, 32, 564, DateTimeKind.Unspecified).AddTicks(4802), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "System Administrator",
                            Email = "admin@example.com",
                            Industry = "Administration",
                            Location = "Remote",
                            Name = "Admin System",
                            Pass = "admin123",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("aabu_project.Models.ApplicationJob", b =>
                {
                    b.HasOne("aabu_project.Models.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aabu_project.Models.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("aabu_project.Models.Education", b =>
                {
                    b.HasOne("aabu_project.Models.Resume", "Resume")
                        .WithMany("Educations")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("aabu_project.Models.Experience", b =>
                {
                    b.HasOne("aabu_project.Models.Resume", "Resume")
                        .WithMany("Experiences")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("aabu_project.Models.FollowCompany", b =>
                {
                    b.HasOne("aabu_project.Models.User", "Company")
                        .WithMany("Followers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("aabu_project.Models.User", "User")
                        .WithMany("FollowedCompanies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("aabu_project.Models.Job", b =>
                {
                    b.HasOne("aabu_project.Models.Category", "Category")
                        .WithMany("Jobs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aabu_project.Models.User", "User")
                        .WithMany("Jobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("aabu_project.Models.Notification", b =>
                {
                    b.HasOne("aabu_project.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("aabu_project.Models.Resume", b =>
                {
                    b.HasOne("aabu_project.Models.User", "User")
                        .WithMany("Resumes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("aabu_project.Models.Role", b =>
                {
                    b.HasOne("aabu_project.Models.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("aabu_project.Models.SavedJob", b =>
                {
                    b.HasOne("aabu_project.Models.Job", "Job")
                        .WithMany("SavedJobs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("aabu_project.Models.User", "User")
                        .WithMany("SavedJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("aabu_project.Models.Skill", b =>
                {
                    b.HasOne("aabu_project.Models.Resume", "Resume")
                        .WithMany("Skills")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("aabu_project.Models.Category", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("aabu_project.Models.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("SavedJobs");
                });

            modelBuilder.Entity("aabu_project.Models.Resume", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("aabu_project.Models.User", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("FollowedCompanies");

                    b.Navigation("Followers");

                    b.Navigation("Jobs");

                    b.Navigation("Notifications");

                    b.Navigation("Resumes");

                    b.Navigation("Roles");

                    b.Navigation("SavedJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
