import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('lang') || 'en');
    const [dir, setDir] = useState(language === 'ar' ? 'rtl' : 'ltr');

    useEffect(() => {
        localStorage.setItem('lang', language);
        setDir(language === 'ar' ? 'rtl' : 'ltr');
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language]);

    const toggleLanguage = () => {
        setLanguage((prev) => (prev === 'en' ? 'ar' : 'en'));
    };

    const translations = {
        en: {
            search: "Search...",
            signIn: "Sign In",
            register: "Register",
            dashboard: "Dashboard",
            findJobs: "Find Jobs",
            findCandidates: "Find Candidates",
            faq: "FAQ",
            faqTitle: "Frequently Asked Questions",
            faq1Q: "How do I apply for a job?",
            faq1A: "To apply for a job, navigate to the 'Find Jobs' page, click on a job that interests you, and then click the 'Apply Now' button. You can also add a brief note and your CV.",
            faq2Q: "How can I create an employer account?",
            faq2A: "During registration, select 'Employer' as your role. Once registered, you can post jobs, manage applicants, and view candidate profiles.",
            faq3Q: "Can I save jobs to apply later?",
            faq3A: "Yes! Click the heart icon on any job listing to save it. You can access all your saved jobs from your dashboard.",
            faq4Q: "How do I build a resume using the Resume Builder?",
            faq4A: "Go to the 'Resume Builder' section in your dashboard. Enter your personal details, experience, education, and skills, then download or use it directly on the platform.",
            faq5Q: "Is my personal information secure?",
            faq5A: "Absolutely. We use industry-standard encryption to protect your data and only share your contact information with employers when you apply for a job.",
            faq6Q: "How can I contact support?",
            faq6A: "You can reach us through our 'Contact Us' page or by emailing info@smartjob.com. Our support team is available 24/7.",
            stillHaveQuestions: "Still have questions?",
            contactSupportDesc: "Can't find the answer you're looking for? Please contact our friendly team.",
            companies: "Companies",
            candidates: "Candidates",
            settings: "Settings",
            logout: "Logout",
            activeJobs: "Active Jobs",
            activeCompanies: "Companies",
            activeCandidates: "Candidates",
            heroTitle: "Find Your Dream Job Today with InsightCV",
            heroSubtitle: "Join over 10,000+ professionals and discover the best opportunities in tech, design, and management.",
            jobTitlePlaceholder: "Job title or keyword",
            locationPlaceholder: "Location",
            searchJobs: "Search Jobs",
            featuredJobs: "Featured Jobs",
            viewAll: "View All Jobs",
            details: "Details",
            loginHeader: "Welcome Back",
            loginSubtitle: "Enter your details to access your account",
            registerHeader: "Create an Account",
            registerSubtitle: "Join our platform to find your next career move",
            email: "Email Address",
            password: "Password",
            fullName: "Full Name",
            role: "Select your role",
            jobSeeker: "Job Seeker",
            company: "Company",
            haveAccount: "Already have an account?",
            noAccount: "Don't have an account?",
            loginBtn: "Sign In",
            registerBtn: "Create Account",
            emailRequired: "Email is required",
            passRequired: "Password is required",
            nameRequired: "Full Name is required",
            passMismatch: "Passwords do not match",
            // Employer Home Translations
            employerHeroTitle: "Find Top Talent Today with InsightCV",
            employerHeroSubtitle: "Join our platform to discover the best professionals in tech, design, and management.",
            searchCandidates: "Search Candidates",
            topTalent: "Top Talent",
            featuredTalent: "Featured Talent",
            candidatePlaceholder: "Skill or Job Title",
            forEmployers: "For Employers",
            forJobSeekers: "For Job Seekers",
            // New Translations
            filters: "Filters",
            jobType: "Job Type",
            category: "Category",
            allCategories: "All Categories",
            salaryRange: "Salary Range",
            allTypes: "All Types",
            fullTime: "Full-time",
            partTime: "Part-time",
            contract: "Contract",
            remote: "Remote",
            onSite: "On-site",
            hybrid: "Hybrid",
            workMode: "Work Mode",
            applyNow: "Apply Now",
            saveJob: "Save Job",
            saved: "Saved",
            jobDescription: "Job Description",
            responsibilities: "Responsibilities",
            requirements: "Requirements",
            savedJobs: "Saved Jobs",
            profile: "Profile",
            notifications: "Notifications",
            resumeBuilder: "Resume Builder",
            personalInfo: "Personal Info",
            experience: "Experience",
            education: "Education",
            skills: "Skills",
            livePreview: "Live Preview",
            saveProfile: "Save Profile",
            markAsRead: "Mark as read",
            clearAll: "Clear all",
            noNotifications: "No notifications",
            noSavedJobs: "No saved jobs yet",
            addExperience: "Add Experience",
            addEducation: "Add Education",
            jobTitle: "Job Title",
            companyName: "Company Name",
            startDate: "Start Date",
            endDate: "End Date",
            degree: "Degree",
            institution: "Institution",
            aboutMe: "About Me",
            // Dashboard & Home
            popularCategories: "Popular Categories",
            categoriesSubtitle: "Explore jobs by your industry preference",
            handPickedJobs: "Hand-Picked Opportunities",
            overview: "Overview",
            appliedJobs: "Applied Jobs",
            interviews: "Interviews",
            pending: "Pending",
            recentActivity: "Recent Activity",
            recentApplications: "Recent Applications",
            welcomeBack: "Welcome back",
            dashboardSubtitle: "Here's what's happening with your job search today.",
            newJobMatch: "New Job Match!",
            jobMatchSubtitle: "matches your profile.",
            totalPostings: "Total Postings",
            messages: "Messages",
            recentApplicants: "Recent Applicants",
            viewProfile: "View Profile",
            accept: "Accept",
            reject: "Reject",
            jobPerformance: "Job Performance",
            performanceMetrics: "Job performance metrics and charts will appear here as you receive more applications.",
            postNewJob: "Post New Job",
            allApplicants: "All Applicants",
            applicantName: "Applicant Name",
            appliedFor: "Applied For",
            status: "Status",
            actions: "Actions",
            reviewing: "Reviewing",
            shortlisted: "Shortlisted",
            hired: "Hired",
            rejected: "Rejected",
            viewResume: "View Resume",
            accepted: "Accepted",
            candidateAccepted: "Candidate Accepted",
            seniorReactDev: "Senior React Developer",
            uiuxDesigner: "UI/UX Designer",
            marketingManager: "Marketing Manager",
            myApplications: "My Applications",
            applicationsSubtitle: "Track the status of jobs you have applied for.",
            noJobsFound: "No jobs found. Start by posting your first job!",
            applied: "Applied",
            myJobs: "My Jobs",
            postedDate: "Posted Date",
            manage: "Manage",
            edit: "Edit",
            delete: "Delete",
            views: "Views",
            active: "Active",
            closed: "Closed",
            confirmDelete: "Confirm Delete",
            deleteUserConfirm: "Delete User",
            deleteJobConfirm: "Delete Job Posting",
            deleteCompanyConfirm: "Delete Company",
            deleteUserConfirmation: "Are you sure you want to delete this user? This action cannot be undone.",
            deleteJobConfirmation: "Are you sure you want to delete this job posting?",
            deleteCompanyConfirmation: "Are you sure you want to delete this company profile and all its associated data?",
            back: "Back",
            submitApplication: "Apply Now",
            alreadyApplied: "Already Applied",
            appliedSuccess: "Application submitted successfully!",
            appliedSuccessMsg: "You successfully applied for {role} at {company}",
            applicationStatusUpdateMsg: "Your application for '{jobTitle}' has been updated to: {status}",
            employerViewedResumeMsg: "{company} viewed your resume",
            applicationReceivedMsg: "Your application for {jobTitle} has been received",
            applicationReceived: "Application Received",
            applicationStatusUpdate: "Application Status Update",
            employerViewedProfileMsg: "An employer viewed your profile",
            signInToApply: "Please sign in to apply",
            applyFor: "Apply for",
            justNow: "Just now",
            anonymousApplicant: "Anonymous Applicant",
            unknownLocation: "Unknown Location",
            securityPolicy: "Security Policy",
            home: "Home",
            reportJob: "Report Job",
            website: "Website",
            linkedin: "LinkedIn",
            unknownCompany: "Unknown Company",
            salaryNegotiable: "Salary Negotiable",
            reportJob: "Report Job",
            website: "Website",
            linkedin: "LinkedIn",
            matchingSubtitle: "Start exploring and saving opportunities that match your profile.",
            allCaughtUp: "You're all caught up! Check back later for updates.",
            welcomeMessage: "Welcome to your notification center. You will see activity here.",
            unreadNotificationsToast: "You have {count} unread notifications",
            phone: "Phone",
            downloadPdf: "Download PDF",
            rolePlaceholder: "language",
            companyPlaceholder: "Company",
            present: "Present",
            postAJob: "Post a Job",
            menu: "Menu",
            changePhoto: "Change Photo",
            uploadPhoto: "Upload Photo",
            footerTagline: "Modern recruitment platform for professionals.",
            platform: "Platform",
            support: "Support",
            legal: "Legal",
            aboutUs: "About Us",
            contactUs: "Contact Us",
            privacyPolicy: "Privacy Policy",
            termsOfService: "Terms of Service",
            copyright: "All rights reserved.",
            chatbotName: "SmartAssistant",
            chatbotWelcome: "Hello! How can I help you today?",
            chatbotPlaceholder: "Type your message...",
            typeAMessage: "Please type a message.",
            uploadFile: "Upload File",
            fileUploaded: "File uploaded successfully!",
            addSkill: "Add Skill",
            graduationYear: "Graduation Year",
            degreePlaceholder: "e.g. Computer Science",
            institutionPlaceholder: "e.g. AABU ",
            skillPlaceholder: "e.g. React",
            exploreCompanies: "Explore Companies",
            companiesSubtitle: "Discover leading organizations and your next career destination.",
            openPositions: "Open Positions",
            employees: "Employees",
            sector: "Sector",
            allSectors: "All Sectors",
            tech: "Technology",
            finance: "Finance",
            healthcare: "Healthcare",
            education_sector: "Education",
            accountSettings: "Account Settings",
            security: "Security",
            notificationPreferences: "Notification Preferences",
            changePassword: "Change Password",
            currentPassword: "Current Password",
            newPassword: "New Password",
            confirmPassword: "Confirm Password",
            emailNotifications: "Email Notifications",
            pushNotifications: "Push Notifications",
            deleteAccount: "Delete Account",
            accountPreferences: "Account Preferences",
            languageAndRegion: "Language & Region",
            oneDayAgo: "1 day ago",
            twoDaysAgo: "2 days ago",
            applicationViewed: "Viewed",
            newMessage: "New Message",
            interviewScheduled: "Interview Scheduled",
            // About Us
            aboutHeroTitle: "Connecting Talent with Opportunity",
            aboutHeroDesc: "InsightCV is more than just a job board. We are a modern recruitment platform dedicated to transforming how people find work and how companies build teams.",
            communityFirst: "Community First",
            communityFirstDesc: "We build tools that empower job seekers and employers to connect meaningfully.",
            smartMatching: "Smart Matching",
            smartMatchingDesc: "Our AI-driven algorithms ensure the right talent finds the right opportunity.",
            secureTrusted: "Secure & Trusted",
            secureTrustedDesc: "Your data privacy and security are our top priorities.",
            innovation: "Innovation",
            innovationDesc: "We continuously evolve to stay ahead of the changing job market trends.",
            ourMission: "Our Mission",
            missionDesc: "To provide a seamless, transparent, and efficient recruitment experience for everyone. We believe that finding a job should be as easy as sharing your vision, and finding talent should be as simple as stating your needs.",
            successStories: "Success Stories",
            verifiedCompanies: "Verified Companies",
            countries: "Countries",
            ourValues: "Our Core Values",
            // Contact Us
            contactHeroTitle: "Get in Touch",
            contactHeroDesc: "Have questions or feedback? We'd love to hear from you. Our team is here to help you 24/7.",
            emailUs: "Email Us",
            callUs: "Call Us",
            visitUs: "Visit Us",
            workingHours: "Working Hours",
            workingHoursSunThu: "Sun - Thu: 9:00 AM - 6:00 PM",
            workingHoursSat: "Sat: 10:00 AM - 2:00 PM",
            sendUsMessage: "Send us a Message",
            subject: "Subject",
            subjectPlaceholder: "How can we help?",
            message: "Message",
            messagePlaceholder: "Tell us more about your inquiry...",
            sendMessage: "Send Message",
            contactSuccess: "Thank you! Your message has been sent.",
            visitUsAmman: "King Hussein Business Park, Amman, Jordan",
            applicationViewedMsg: "TechVision viewed your application for \"Senior Frontend Engineer\"",
            newMessageMsg: "You have a new message from the HR department at CreativePulse",
            interviewScheduledMsg: "Your interview with DataFlow has been scheduled for tomorrow at 10:00 AM",
            newApplication: "New Application",
            newApplicationMsg: "You received a new application for {role} from {name}",
            newApplicantsSummary: "You have {count}+ new applicants for your job postings.",
            candidateMessage: "{name} sent you a message regarding the {role} position.",
            interviewReminder: "Interview Reminder",
            interviewReminderMsg: "You have an interview scheduled with {name} today at {time}",
            twoHoursAgo: "2 hours ago",
            oneDayAgo: "1 day ago",
            jobDescription: "Job Description",
            responsibilities: "Responsibilities",
            requirements: "Requirements",
            applySubtitle: "Interested in this position? Apply directly through our platform.",
            yourName: "Your Name",
            emailExample: "email@example.com",
            seniorFrontendEngineer: "Senior Frontend Engineer",
            techVision: "TechVision",
            remoteLocation: "Remote",
            salaryExample: "$120,000 - $160,000",
            jobDescriptionText: "We are looking for a Senior Frontend Engineer to join our core product team. You will be responsible for building high-performance, accessible, and beautiful user interfaces using React and modern CSS.",
            resp1: "Architect and build scalable frontend components.",
            resp2: "Collaborate with designers to implement pixel-perfect UIs.",
            resp3: "Optimize application performance and accessibility.",
            resp4: "Mentor junior engineers and conduct code reviews.",
            req1: "5+ years of experience with React.",
            req2: "Strong proficiency in TypeScript and CSS/SASS.",
            req3: "Experience with state management (Redux/Zustand).",
            req4: "Understanding of CI/CD and modern frontend tooling.",
            defaultBio: "Software Engineer with a passion for building beautiful and functional user interfaces.",
            defaultLocation: "Amman, Jordan",
            postJobHeader: "Post a New Job",
            postJobSubtitle: "Fill out the information below to find your next great hire.",
            step1: "Basic Information",
            step2: "Job Details",
            step3: "Review & Post",
            jobDescriptionPlaceholder: "Provide a detailed description of the role...",
            category: "Category",
            selectCategory: "Select Category",
            design: "Design",
            engineering: "Engineering",
            marketing: "Marketing",
            management: "Management",
            salaryNegotiable: "Salary Negotiable",
            benefits: "Benefits",
            benefitsPlaceholder: "e.g., Health Insurance, Flexible Hours",
            publishJob: "Publish Job",
            nextStep: "Next Step",
            responsibilitiesPlaceholder: "Describe the key responsibilities for this role...",
            requirementsPlaceholder: "What skills and experience are required?",
            other: "Other",
            jobPostedSuccess: "Job Posted Successfully!",
            jobPostedSubtitle: "Your job listing is now live and visible to candidates.",
            goToDashboard: "Go to Dashboard",
            createAnother: "Create Another Listing",
            // Admin Translations
            adminDashboard: "Admin Dashboard",
            totalUsers: "Total Users",
            totalCompanies: "Total Companies",
            totalRevenue: "Total Revenue",
            platformActivity: "Platform Activity",
            recentUsers: "Recent Users",
            manageUsers: "Manage Users",
            searchUsers: "Search users by name or email...",
            allRoles: "All Roles",
            suspend: "Suspend",
            activate: "Activate",
            registrationDate: "Registration Date",
            userRole: "Role",
            emailAddress: "Email Address",
            suspended: "Suspended",
            manageJobs: "Manage Jobs",
            manageCompanies: "Manage Companies",
            platformSettings: "Platform Settings",
            searchCompanies: "Search companies by name...",
            allStatuses: "All Statuses",
            approve: "Approve",
            approved: "Approved",
            pendingApproval: "Pending",
            company: "Company",
            postedBy: "Posted By",
            location: "Location",
            industry: "Industry",
            joinDate: "Join Date",
            generalSettings: "General Settings",
            siteName: "Site Name",
            contactEmail: "Contact Email",
            saveChanges: "Save Changes",
            securitySettings: "Security Settings",
            requireEmailVerification: "Require Email Verification",
            maintenanceMode: "Maintenance Mode",
            systemSettings: "System Settings",
            cacheManagement: "Cache Management",
            clearCache: "Clear Cache",
            twoFactorAuth: "Two-Factor Authentication (2FA)",
            passwordPolicy: "Strict Password Policy",
            adminJobsApproval: "Jobs Pending Approval",
            adminJobsApprovalMsg: "2+ new jobs have been posted and need your approval.",
            adminCompanyApproval: "New Companies",
            adminCompanyApprovalMsg: "3 new companies registered on the platform today.",
            systemUpdate: "System Update",
            systemUpdateMsg: "The platform was successfully updated to version 1.2.0.",
            resumeNamePlaceholder: "Name",
            resumeEmailPlaceholder: "e.g. user@example.com",
            resumePhonePlaceholder: "Phone Number",
            resumeAboutPlaceholder: "Tell us about your background, skills, and goals...",
            resumeRolePlaceholder: "e.g. Software Engineer",
            resumeCompanyPlaceholder: "e.g. TechCorp",
            resumeDatePlaceholder: "e.g. MM/YYYY or YYYY",
            // Cities
            amman: "Amman",
            irbid: "Irbid",
            zarqa: "Zarqa",
            balqa: "Balqa",
            madaba: "Madaba",
            karak: "Karak",
            tafilah: "Tafilah",
            maan: "Ma'an",
            aqaba: "Aqaba",
            mafraq: "Mafraq",
            jerash: "Jerash",
            ajloun: "Ajloun",
            selectLocation: "Select Location",
            // Dashboard Months
            jan: "Jan", feb: "Feb", mar: "Mar", apr: "Apr", may: "May", jun: "Jun",
            jul: "Jul", aug: "Aug", sep: "Sep", oct: "Oct", nov: "Nov", dec: "Dec",
            // More Statuses
            upcoming: "Upcoming",
            views: "Views",
            performance: "Performance",
            applicationSent: "Application Sent",
            resumeViewed: "Resume Viewed",
            candidateRejected: "Candidate Rejected",
            uiDesigner: "UI Designer",
            backendDeveloper: "Backend Developer",
            userProfile: "User Profile",
            profileUpdated: "Profile updated successfully!",
            emailNotifDesc: "Receive updates via your registered email.",
            pushNotifDesc: "Desktop and mobile browser alerts.",
            switchToArabic: "Switch to Arabic",
            switchToEnglish: "Switch to English",
            deleteAccountWarning: "Once you delete your account, there is no going back. Please be certain."
        },
        ar: {
            search: "ابحث...",
            signIn: "تسجيل الدخول",
            register: "إنشاء حساب",
            dashboard: "لوحة التحكم",
            findJobs: "البحث عن وظائف",
            findCandidates: "البحث عن مرشحين",
            companies: "الشركات",
            candidates: "المرشحون",
            settings: "الإعدادات",
            logout: "تسجيل الخروج",
            activeJobs: "وظائف نشطة",
            activeCompanies: "شركات",
            activeCandidates: "مرشحون",
            heroTitle: "جد وظيفة أحلامك اليوم مع InsightCV",
            heroSubtitle: "انضم إلى أكثر من 10,000 محترف واكتشف أفضل الفرص في مجالات التقنية والتصميم والإدارة.",
            jobTitlePlaceholder: "عنوان الوظيفة أو الكلمة المفتاحية",
            locationPlaceholder: "الموقع",
            searchJobs: "ابحث عن وظائف",
            featuredJobs: "وظائف مميزة",
            viewAll: "عرض كل الوظائف",
            details: "التفاصيل",
            loginHeader: "مرحباً بك مجدداً",
            loginSubtitle: "أدخل بياناتك للوصول إلى حسابك",
            registerHeader: "إنشاء حساب جديد",
            registerSubtitle: "انضم إلى منصتنا لتجد خطوتك المهنية القادمة",
            email: "البريد الإلكتروني",
            password: "كلمة المرور",
            fullName: "الاسم الكامل",
            role: "اختر دورك",
            jobSeeker: "باحث عن عمل",
            company: "شركة",
            haveAccount: "لديك حساب بالفعل؟",
            noAccount: "ليس لديك حساب؟",
            loginBtn: "تسجيل الدخول",
            registerBtn: "إنشاء حساب",
            emailRequired: "البريد الإلكتروني مطلوب",
            passRequired: "كلمة المرور مطلوبة",
            nameRequired: "الاسم الكامل مطلوب",
            passMismatch: "كلمات المرور غير متطابقة",
            // Employer Home Translations
            employerHeroTitle: "ابحث عن أفضل المواهب اليوم مع InsightCV",
            employerHeroSubtitle: "انضم إلى منصتنا لاكتشاف أفضل المحترفين في مجالات التقنية والتصميم والإدارة.",
            searchCandidates: "البحث عن مرشحين",
            topTalent: "أفضل المواهب",
            featuredTalent: "مواهب مميزة",
            candidatePlaceholder: "المهارة أو المسمى الوظيفي",
            forEmployers: "لأصحاب العمل",
            forJobSeekers: "للباحثين عن عمل",
            // New Translations
            filters: "الفلاتر",
            jobType: "نوع الوظيفة",
            category: "الفئة",
            allCategories: "كل الفئات",
            salaryRange: "نطاق الراتب",
            allTypes: "كل الأنواع",
            fullTime: "دوام كامل",
            partTime: "دوام جزئي",
            contract: "عقد",
            remote: "عن بعد",
            onSite: "ميداني",
            hybrid: "هجين",
            workMode: "طبيعة العمل",
            applyNow: "قدم الآن",
            saveJob: "حفظ الوظيفة",
            saved: "تم الحفظ",
            jobDescription: "وصف الوظيفة",
            responsibilities: "المسؤوليات",
            requirements: "المتطلبات",
            savedJobs: "الوظائف المحفوظة",
            profile: "الملف الشخصي",
            notifications: "التنبيهات",
            resumeBuilder: "منشئ السيرة الذاتية",
            personalInfo: "المعلومات الشخصية",
            experience: "الخبرة",
            education: "التعليم",
            skills: "المهارات",
            livePreview: "معاينة مباشرة",
            saveProfile: "حفظ الملف",
            markAsRead: "تحديد كمقروء",
            clearAll: "مسح الكل",
            noNotifications: "لا توجد تنبيهات",
            noSavedJobs: "لا توجد وظائف محفوظة بعد",
            addExperience: "إضافة خبرة",
            addEducation: "إضافة تعليم",
            jobTitle: "المسمى الوظيفي",
            companyName: "اسم الشركة",
            startDate: "تاريخ البدء",
            endDate: "تاريخ الانتهاء",
            degree: "الدرجة العلمية",
            institution: "المؤسسة التعليمية",
            aboutMe: "نبذة عني",
            // Dashboard & Home
            popularCategories: "الأقسام الشائعة",
            categoriesSubtitle: "استكشف الوظائف حسب اهتماماتك المهنية",
            handPickedJobs: "فرص مختارة بعناية",
            overview: "نظرة عامة",
            appliedJobs: "الوظائف المقدمة",
            interviews: "المقابلات",
            pending: "قيد الانتظار",
            recentActivity: "النشاط الأخير",
            recentApplications: "طلبات التوظيف الأخيرة",
            welcomeBack: "مرحباً بك مجدداً",
            dashboardSubtitle: "إليك آخر التطورات في رحلة بحثك عن عمل اليوم.",
            newJobMatch: "وظيفة جديدة متناسبة!",
            jobMatchSubtitle: "تتناسب مع ملفك الشخصي.",
            totalPostings: "إجمالي المنشورات",
            messages: "الرسائل",
            recentApplicants: "المتقدمون الأخيرون",
            viewProfile: "عرض الملف",
            accept: "قبول",
            reject: "رفض",
            jobPerformance: "أداء الوظائف",
            performanceMetrics: "ستظهر مقاييس أداء الوظائف والرسوم البيانية هنا مع تلقي المزيد من الطلبات.",
            postNewJob: "نشر وظيفة جديدة",
            allApplicants: "كل المتقدمين",
            applicantName: "اسم المتقدم",
            appliedFor: "تقدم لوظيفة",
            status: "الحالة",
            actions: "الإجراءات",
            reviewing: "قيد المراجعة",
            shortlisted: "مقبول مبدئياً",
            hired: "تم التوظيف",
            rejected: "مرفوض",
            viewResume: "عرض السيرة الذاتية",
            accepted: "مقبول",
            candidateAccepted: "تم قبول المرشح",
            seniorReactDev: "مطور ريآكت سينيور",
            uiuxDesigner: "مصمم واجهات المستخدم",
            marketingManager: "مدير تسويق",
            myApplications: "طلباتي",
            applicationsSubtitle: "تتبع حالة الوظائف التي تقدمت لها.",
            noJobsFound: "لم يتم العثور على وظائف، ابدأ بنشر وظيفتك الأولى!",
            applied: "تم التقديم",
            myJobs: "وظائفي المنشورة",
            postedDate: "تاريخ النشر",
            manage: "إدارة",
            edit: "تعديل",
            delete: "حذف",
            views: "المشاهدات",
            active: "نشط",
            closed: "مغلق",
            confirmDelete: "تأكيد الحذف",
            deleteUserConfirm: "حذف المستخدم",
            deleteJobConfirm: "حذف منشور الوظيفة",
            deleteCompanyConfirm: "حذف الشركة",
            deleteUserConfirmation: "هل أنت متأكد من حذف هذا المستخدم؟ لا يمكن التراجع عن هذا الإجراء.",
            deleteJobConfirmation: "هل أنت متأكد من حذف هذا المنشور؟",
            deleteCompanyConfirmation: "هل أنت متأكد من حذف ملف هذه الشركة وجميع البيانات المرتبطة بها؟",
            back: "العودة",
            submitApplication: "قدم الآن",
            alreadyApplied: "تم التقديم مسبقاً",
            appliedSuccess: "تم تقديم الطلب بنجاح!",
            appliedSuccessMsg: "لقد تقدمت بنجاح لوظيفة {role} في {company}",
            applicationStatusUpdateMsg: "تم تحديث حالة طلبك لوظيفة '{jobTitle}' إلى: {status}",
            employerViewedResumeMsg: "قام {company} بمشاهدة سيرتك الذاتية",
            applicationReceivedMsg: "تم استلام طلبك لوظيفة {jobTitle}",
            applicationReceived: "تم استلام الطلب",
            applicationStatusUpdate: "تحديث حالة الطلب",
            employerViewedProfileMsg: "قام صاحب عمل بمشاهدة ملفك الشخصي",
            signInToApply: "الرجاء تسجيل الدخول للتقديم",
            applyFor: "التقديم على وظيفة",
            justNow: "الآن",
            anonymousApplicant: "متقدم مجهول",
            unknownLocation: "موقع غير معروف",
            securityPolicy: "سياسة الأمن",
            home: "الرئيسية",
            reportJob: "الإبلاغ عن وظيفة",
            website: "الموقع الإلكتروني",
            linkedin: "لينكد إن",
            unknownCompany: "شركة غير معروفة",
            salaryNegotiable: "الراتب قابل للتفاوض",
            reportJob: "الإبلاغ عن وظيفة",
            website: "الموقع الإلكتروني",
            linkedin: "لينكد إن",

            matchingSubtitle: "ابدأ في استكشاف وحفظ الفرص التي تتناسب مع ملفك الشخصي.",
            allCaughtUp: "لقد شاهدت كل التنبيهات! تفقد هذه الصفحة لاحقاً للمزيد.",
            welcomeMessage: "أهلاً بك في مركز التنبيهات. ستظهر لك هنا جميع التحديثات والنشاطات.",
            unreadNotificationsToast: "لديك {count} تنبيهات غير مقروءة",
            phone: "الهاتف",
            downloadPdf: "تحميل الملف",
            rolePlaceholder: "اللغة",
            companyPlaceholder: "اسم الشركة",
            present: "الحالي",
            postAJob: "نشر وظيفة",
            menu: "القائمة",
            changePhoto: "تغيير الصورة",
            uploadPhoto: "رفع صورة",
            footerTagline: "منصة توظيف حديثة للمحترفين.",
            platform: "المنصة",
            support: "الدعم",
            legal: "قانوني",
            aboutUs: "من نحن",
            contactUs: "اتصل بنا",
            privacyPolicy: "سياسة الخصوصية",
            termsOfService: "شروط الخدمة",
            copyright: "جميع الحقوق محفوظة.",
            chatbotName: "المساعد الذكي",
            chatbotWelcome: "مرحباً! كيف يمكنني مساعدتك اليوم؟",
            chatbotPlaceholder: "اكتب رسالتك هنا...",
            typeAMessage: "يرجى كتابة رسالة.",
            uploadFile: "رفع ملف",
            fileUploaded: "تم رفع الملف بنجاح!",
            addSkill: "إضافة مهارة",
            graduationYear: "سنة التخرج",
            degreePlaceholder: "مثلاً: بكالوريوس هندسة برمجيات",
            institutionPlaceholder: "مثلاً: جامعة الملك سعود",
            skillPlaceholder: "مثلاً: ريآكت",
            exploreCompanies: "استكشف الشركات",
            companiesSubtitle: "اكتشف المؤسسات الرائدة ووجهتك المهنية القادمة.",
            openPositions: "وظائف شاغرة",
            employees: "موظف",
            sector: "القطاع",
            allSectors: "جميع القطاعات",
            tech: "التكنولوجيا",
            finance: "المالية",
            healthcare: "الرعاية الصحية",
            education_sector: "التعليم",
            accountSettings: "إعدادات الحساب",
            security: "الأمان",
            notificationPreferences: "تفضيلات التنبيهات",
            changePassword: "تغيير كلمة المرور",
            currentPassword: "كلمة المرور الحالية",
            newPassword: "كلمة المرور الجديدة",
            confirmPassword: "تأكيد كلمة المرور",
            emailNotifications: "تنبيهات البريد الإلكتروني",
            pushNotifications: "تنبيهات الهاتف",
            deleteAccount: "حذف الحساب",
            saveChanges: "حفظ التغييرات",
            accountPreferences: "تفضيلات الحساب",
            languageAndRegion: "اللغة والمنطقة",
            oneDayAgo: "منذ يوم",
            twoDaysAgo: "منذ يومين",
            applicationViewed: "تمت المشاهدة",
            newMessage: "رسالة جديدة",
            interviewScheduled: "تم تحديد موعد المقابلة",
            applicationViewedMsg: "شاهدت شركة TechVision طلبك لوظيفة \"Senior Frontend Engineer\"",
            newMessageMsg: "لديك رسالة جديدة من قسم الموارد البشرية في CreativePulse",
            interviewScheduledMsg: "تم تحديد موعد لمقابلتك مع DataFlow غداً الساعة 10:00 صباحاً",
            newApplication: "طلب توظيف جديد",
            newApplicationMsg: "لقد تلقيت طلب توظيف جديد لوظيفة {role} من {name}",
            newApplicantsSummary: "لديك {count}+ متقدمين جدد لوظائفك المنشورة.",
            candidateMessage: "أرسل لك {name} رسالة بخصوص وظيفة {role}.",
            interviewReminder: "تذكير بموعد مقابلة",
            interviewReminderMsg: "لديك مقابلة محددة مع {name} اليوم في تمام الساعة {time}",
            twoHoursAgo: "منذ ساعتين",
            oneDayAgo: "منذ يوم",
            jobDescription: "وصف الوظيفة",
            responsibilities: "المسؤوليات",
            requirements: "المتطلبات",
            applySubtitle: "مهتم بهذه الوظيفة؟ قدم مباشرة من خلال منصتنا.",
            yourName: "اسمك",
            emailExample: "email@example.com",
            seniorFrontendEngineer: "مهندس واجهات أمامية",
            techVision: "تيك فيجن",
            remoteLocation: "عن بعد",
            salaryExample: "120,000$ - 160,000$",
            jobDescriptionText: "نحن نبحث عن مهندس واجهات أمامية سينيور للانضمام إلى فريقنا الأساسي. ستكون مسؤولاً عن بناء واجهات مستخدم عالية الأداء ويمكن الوصول إليها وجميلة باستخدام React و CSS الحديث.",
            resp1: "بناء وتطوير مكونات واجهة أمامية قابلة للتوسع.",
            resp2: "التعاون مع المصممين لتنفيذ واجهات مستخدم بدقة متناهية.",
            resp3: "تحسين أداء التطبيق وسهولة الوصول.",
            resp4: "توجيه المهندسين المبتدئين وإجراء مراجعات الكود.",
            req1: "أكثر من 5 سنوات من الخبرة في React.",
            req2: "إتقان قوي لـ TypeScript و CSS/SASS.",
            req3: "خبرة في إدارة الحالة (Redux/Zustand).",
            req4: "فهم CI/CD وأدوات الواجهة الأمامية الحديثة.",
            defaultBio: "مهندس برمجيات شغوف ببناء واجهات مستخدم جميلة ووظيفية.",
            defaultLocation: "عمان، الأردن",
            postJobHeader: "نشر وظيفة جديدة",
            postJobSubtitle: "املأ المعلومات أدناه للعثور على موظفك المتميز القادم.",
            step1: "معلومات أساسية",
            step2: "تفاصيل الوظيفة",
            step3: "المراجعة والنشر",
            jobDescriptionPlaceholder: "قدم وصفاً مفصلاً للدور الوظيفي...",
            category: "الفئة",
            selectCategory: "اختر الفئة",
            design: "التصميم",
            engineering: "الهندسة",
            marketing: "التسويق",
            management: "الإدارة",
            salaryNegotiable: "الراتب قابل للتفاوض",
            benefits: "المميزات",
            benefitsPlaceholder: "مثلاً: تأمين صحي، ساعات عمل مرنة",
            publishJob: "نشر الوظيفة",
            nextStep: "الخطوة التالية",
            responsibilitiesPlaceholder: "صف المسؤوليات الرئيسية لهذا الدور...",
            requirementsPlaceholder: "ما هي المهارات والخبرات المطلوبة؟",
            other: "أخرى",
            jobPostedSuccess: "تم نشر الوظيفة بنجاح!",
            jobPostedSubtitle: "قائمتك الآن مباشرة ومرئية للمرشحين.",
            goToDashboard: "الذهاب إلى لوحة التحكم",
            createAnother: "إنشاء قائمة أخرى",
            // Admin Translations
            adminDashboard: "لوحة تحكم المسؤول",
            totalUsers: "إجمالي المستخدمين",
            totalCompanies: "إجمالي الشركات",
            totalRevenue: "إجمالي الإيرادات",
            platformActivity: "نشاط المنصة",
            recentUsers: "المستخدمين الجدد",
            manageUsers: "إدارة المستخدمين",
            searchUsers: "ابحث عن المستخدمين بالاسم أو البريد...",
            allRoles: "كل الأدوار",
            suspend: "إيقاف",
            activate: "تفعيل",
            registrationDate: "تاريخ التسجيل",
            userRole: "الدور",
            emailAddress: "البريد الإلكتروني",
            suspended: "موقوف",
            manageJobs: "إدارة الوظائف",
            manageCompanies: "إدارة الشركات",
            platformSettings: "إعدادات المنصة",
            searchCompanies: "ابحث عن الشركات بالاسم...",
            allStatuses: "كل الحالات",
            approve: "موافقة",
            approved: "مقبول",
            pendingApproval: "قيد الانتظار",
            company: "شركة",
            postedBy: "نشر بواسطة",
            location: "الموقع",
            industry: "القطاع",
            joinDate: "تاريخ الانضمام",
            generalSettings: "الإعدادات العامة",
            siteName: "اسم الموقع",
            contactEmail: "البريد الإلكتروني للاتصال",
            saveChanges: "حفظ التغييرات",
            securitySettings: "إعدادات الأمان",
            requireEmailVerification: "طلب التحقق من البريد الإلكتروني",
            maintenanceMode: "وضع الصيانة",
            systemSettings: "إعدادات النظام",
            cacheManagement: "إدارة ذاكرة التخزين المؤقت",
            clearCache: "مسح الذاكرة المؤقتة",
            twoFactorAuth: "المصادقة الثنائية (2FA)",
            passwordPolicy: "سياسة مرور صارمة",
            adminJobsApproval: "وظائف بانتظار الموافقة",
            adminJobsApprovalMsg: "تم نشر أكثر من وظيفتين بانتظار موافقتك.",
            adminCompanyApproval: "شركات جديدة",
            adminCompanyApprovalMsg: "سجلت 3 شركات جديدة في المنصة اليوم.",
            systemUpdate: "تحديث النظام",
            systemUpdateMsg: "تم تحديث المنصة بنجاح إلى الإصدار v1.2.0.",
            resumeNamePlaceholder: "مثل: أحمد محمد",
            resumeEmailPlaceholder: "مثل: ahmed@example.com",
            resumePhonePlaceholder: "مثل: +962 7 1234 5678",
            resumeAboutPlaceholder: "حدثنا عن خلفيتك ومهاراتك وأهدافك...",
            resumeRolePlaceholder: "مثل: مهندس برمجيات",
            resumeCompanyPlaceholder: "مثل: شركة التقنية",
            resumeDatePlaceholder: "مثل: شهر/سنة أو سنة",
            // Cities
            amman: "عمان",
            irbid: "إربد",
            zarqa: "الزرقاء",
            balqa: "البلقاء",
            madaba: "مأدبا",
            karak: "الكرك",
            tafilah: "الطفيلة",
            maan: "معان",
            aqaba: "العقبة",
            mafraq: "المفرق",
            jerash: "جرش",
            ajloun: "عجلون",
            selectLocation: "اختر الموقع",
            // Dashboard Months
            jan: "يناير", feb: "فبراير", mar: "مارس", apr: "أبريل", may: "مايو", jun: "يونيو",
            jul: "يوليو", aug: "أغسطس", sep: "سبتمبر", oct: "أكتوبر", nov: "نوفمبر", dec: "ديسمبر",
            // More Statuses
            upcoming: "قادم",
            views: "المشاهدات",
            performance: "الأداء",
            applicationSent: "تم إرسال الطلب",
            resumeViewed: "تمت مشاهدة السيرة الذاتية",
            candidateRejected: "تم رفض المرشح",
            uiDesigner: "مصمم واجهات",
            backendDeveloper: "مطور خلفية",
            userProfile: "ملف المستخدم",
            profileUpdated: "تم تحديث الملف الشخصي بنجاح!",
            emailNotifDesc: "استلم التنبيهات عبر بريدك الإلكتروني المسجل.",
            pushNotifDesc: "تنبيهات المتصفح على الحاسوب والهاتف.",
            switchToArabic: "التحويل للعربية",
            switchToEnglish: "التحويل للإنجليزية",
            deleteAccountWarning: "بمجرد حذف حسابك، لن تتمكن من التراجع. يرجى التأكد.",
            // About Us
            aboutHeroTitle: "ربط المواهب بـالفرص",
            faq: "الأسئلة الشائعة",
            faqTitle: "الأسئلة الشائعة",
            faq1Q: "كيف يمكنني التقديم لوظيفة؟",
            faq1A: "للتقديم على وظيفة، انتقل إلى صفحة 'البحث عن وظائف'، واضغط على الوظيفة التي تهمك، ثم اضغط على زر 'تقدم الآن'. يمكنك أيضاً إضافة ملاحظة سيرة ذاتية.",
            faq2Q: "كيف يمكنني إنشاء حساب صاحب عمل؟",
            faq2A: "أثناء التسجيل، اختر 'صاحب عمل' كدورك. بمجرد التسجيل، يمكنك نشر الوظائف وإدارة المتقدمين وعرض ملفات المرشحين.",
            faq3Q: "هل يمكنني حفظ الوظائف للتقديم لاحقاً؟",
            faq3A: "نعم! اضغط على أيقونة القلب في أي قائمة وظائف لحفظها. يمكنك الوصول إلى جميع وظائفك المحفوظة من لوحة التحكم الخاصة بك.",
            faq4Q: "كيف يمكنني بناء سيرة ذاتية باستخدام منشئ السير الذاتية؟",
            faq4A: "انتقل إلى قسم 'منشئ السير الذاتية' في لوحة التحكم الخاصة بك. أدخل بياناتك الشخصية وخبراتك وتعليمك ومهاراتك، ثم قم بتحميلها أو استخدامها مباشرة على المنصة.",
            faq5Q: "هل معلوماتي الشخصية آمنة؟",
            faq5A: "بالتأكيد. نحن نستخدم تشفيراً قياسياً لحماية بياناتك ونشارك معلومات الاتصال الخاصة بك فقط مع أصحاب العمل عند التقديم لوظيفة.",
            faq6Q: "كيف يمكنني الاتصال بالدعم الفني؟",
            faq6A: "يمكنك الوصول إلينا من خلال صفحة 'اتصل بنا' أو عن طريق البريد الإلكتروني info@smartjob.com. فريق الدعم متاح على مدار الساعة.",
            stillHaveQuestions: "هل لا تزال لديك أسئلة؟",
            contactSupportDesc: "لا تجد الإجابة التي تبحث عنها؟ يرجى الاتصال بفريقنا الودود.",
            aboutHeroDesc: "InsightCV هي أكثر من مجرد لوحة وظائف. نحن منصة توظيف حديثة مكرسة لتغيير كيفية عثور الأشخاص على عمل وكيفية بناء الشركات للفرق.",
            communityFirst: "المجتمع أولاً",
            communityFirstDesc: "نحن نبني أدوات تمكن الباحثين عن عمل وأصحاب العمل من التواصل بشكل هادف.",
            smartMatching: "المطابقة الذكية",
            smartMatchingDesc: "تضمن خوارزمياتنا المدعومة بالذكاء الاصطناعي عثور الموهبة المناسبة على الفرصة المناسبة.",
            secureTrusted: "آمن وموثوق",
            secureTrustedDesc: "خصوصية بياناتك وأمانها هما أولوياتنا القصوى.",
            innovation: "الابتكار",
            innovationDesc: "نحن نتطور باستمرار للبقاء في طليعة اتجاهات سوق العمل المتغيرة.",
            ourMission: "مهمتنا",
            missionDesc: "توفير تجربة توظيف سلسة وشفافة وفعالة للجميع. نحن نؤمن بأن العثور على وظيفة يجب أن يكون سهلاً مثل مشاركة رؤيتك، والعثور على المواهب يجب أن يكون بسيطاً مثل تحديد احتياجاتك.",
            successStories: "قصص النجاح",
            verifiedCompanies: "شركات موثقة",
            countries: "دولة",
            ourValues: "قيمنا الأساسية",
            // Contact Us
            contactHeroTitle: "تواصل معنا",
            contactHeroDesc: "لديك أسئلة أو ملاحظات؟ نود السماع منك. فريقنا هنا لمساعدتك على مدار الساعة.",
            emailUs: "راسلنا بريدياً",
            callUs: "اتصل بنا",
            visitUs: "قم بزيارتنا",
            workingHours: "ساعات العمل",
            workingHoursSunThu: "الأحد - الخميس: 9:00 صباحاً - 6:00 مساءً",
            workingHoursSat: "السبت: 10:00 صباحاً - 2:00 مساءً",
            sendUsMessage: "أرسل لنا رسالة",
            subject: "الموضوع",
            subjectPlaceholder: "كيف يمكننا مساعدتك؟",
            message: "الرسالة",
            messagePlaceholder: "أخبرنا المزيد عن استفسارك...",
            sendMessage: "إرسال الرسالة",
            contactSuccess: "شكراً لك! تم إرسال رسالتك بنجاح.",
            visitUsAmman: "مجمع الملك حسين للأعمال، عمان، الأردن",
        }
    };

    const t = (key, params = {}) => {
        let text = translations[language][key] || key;
        Object.keys(params).forEach(param => {
            text = text.replace(`{${param}}`, params[param]);
        });
        return text;
    };

    return (
        <LanguageContext.Provider value={{ language, dir, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
};
